[package]
name = "neural_network"
version = "0.1.0"
edition = "2021"

[profile.release]
debug = true

[dev-dependencies]
criterion = "0.3"

[dependencies]
nalgebra="0.31.0"
rand = "0.8.5"
csv = "1.1.0"
ctrlc = "3.2.2"

[[bench]]
name = "data"
harness = false